language: python

python:
  - 3.5

services: postgresql

env:
  global:
  - DJANGO_SETTINGS_MODULE="base_site.settings"
  - PYTHONPATH="/home/travis/build/belfastcares/belfast-cares-service"
  - PIP_USE_MIRRORS=true
  - DATABASE_URL='postgres://admin:bcadminpass123@localhost:5432/belfastcares'

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE belfastcares;" -U postgres
  - psql -d belfastcares -c "CREATE USER admin WITH PASSWORD 'bcadminpass123'"
  - psql -c "ALTER USER admin CREATEDB;"

script:
  - python manage.py test
